#include <cairo.h>
#include <cairo-ft.h>
#include <ft2build.h>
#include FT_FREETYPE_H
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <math.h>

// Output file
FILE *out;

// Helper to write Zig header
void write_header() {
    fprintf(out,
        "// Generated by tools/fontgen.c \xe2\x80\x94 do not edit by hand.\n"
        "\n"
        "pub const Glyph = struct {\n"
        "    codepoint: u32,\n"
        "    width: u16,\n"
        "    height: u16,\n"
        "    advance_x: u16,\n"
        "    bearing_x: i16,\n"
        "    bearing_y: i16,\n"
        "    data: []const u8,\n"
        "};\n"
        "\n"
        "pub const Font = struct {\n"
        "    height: u16,\n"
        "    ascent: u16,\n"
        "    descent: u16,\n"
        "    /// Sorted by codepoint so `get` can binary search.\n"
        "    glyphs: []const Glyph,\n"
        "\n"
        "    pub fn get(self: *const Font, codepoint: u32) ?Glyph {\n"
        "        var lo: usize = 0;\n"
        "        var hi: usize = self.glyphs.len;\n"
        "        while (lo < hi) {\n"
        "            const mid = lo + (hi - lo) / 2;\n"
        "            const cp = self.glyphs[mid].codepoint;\n"
        "            if (cp == codepoint) return self.glyphs[mid];\n"
        "            if (cp < codepoint) {\n"
        "                lo = mid + 1;\n"
        "            } else {\n"
        "                hi = mid;\n"
        "            }\n"
        "        }\n"
        "        return null;\n"
        "    }\n"
        "};\n");
}

// Ascending codepoint order, required by Font.get's binary search.
static int compare_codepoints(const void *a, const void *b) {
    uint32_t x = *(const uint32_t *)a, y = *(const uint32_t *)b;
    return (x > y) - (x < y);
}

// Helper to render a single glyph and write its data
void render_glyph(cairo_t *cr, cairo_font_face_t *face, double size, uint32_t codepoint, const char* font_name_suffix, cairo_font_options_t *font_opts) {
    cairo_set_font_face(cr, face);
    cairo_set_font_size(cr, size);
    cairo_set_font_options(cr, font_opts);

    // Get extents
    cairo_text_extents_t extents;
    char utf8[5];
    int len = 0;
    if (codepoint < 0x80) {
        utf8[0] = (char)codepoint;
        utf8[1] = 0;
        len = 1;
    } else if (codepoint < 0x800) {
        utf8[0] = 0xC0 | (codepoint >> 6);
        utf8[1] = 0x80 | (codepoint & 0x3F);
        utf8[2] = 0;
        len = 2;
    } else if (codepoint < 0x10000) {
        utf8[0] = 0xE0 | (codepoint >> 12);
        utf8[1] = 0x80 | ((codepoint >> 6) & 0x3F);
        utf8[2] = 0x80 | (codepoint & 0x3F);
        utf8[3] = 0;
        len = 3;
    }
    
    cairo_text_extents(cr, utf8, &extents);

    int width = (int)ceil(extents.width) + 2; // Add padding
    int height = (int)ceil(extents.height) + 2;
    if (width <= 2) width = (int)extents.x_advance; // For space
    if (height <= 2) height = (int)size;

    // Create surface for glyph
    cairo_surface_t *surface = cairo_image_surface_create(CAIRO_FORMAT_A8, width, height);
    cairo_t *g_cr = cairo_create(surface);
    cairo_set_font_options(g_cr, font_opts);
    
    // Clear
    cairo_set_source_rgba(g_cr, 0, 0, 0, 0);
    cairo_paint(g_cr);
    
    // Draw white text
    cairo_set_source_rgba(g_cr, 1, 1, 1, 1);
    cairo_set_font_face(g_cr, face);
    cairo_set_font_size(g_cr, size);
    
    // Position: -x_bearing to align left, -y_bearing to align top
    cairo_move_to(g_cr, -extents.x_bearing + 1, -extents.y_bearing + 1);
    cairo_show_text(g_cr, utf8);
    
    cairo_surface_flush(surface);
    unsigned char *data = cairo_image_surface_get_data(surface);
    int stride = cairo_image_surface_get_stride(surface);
    
    // Output data array
    fprintf(out, "const glyph_%s_%d_%u = [_]u8{", font_name_suffix, (int)size, codepoint);
    
    // Pack bits (1 bit per pixel)
    // Threshold > 128
    int byte_val = 0;
    int bit_idx = 0;
    int count = 0;
    
    for (int y = 0; y < height; y++) {
        for (int x = 0; x < width; x++) {
            unsigned char alpha = data[y * stride + x];
            if (alpha > 128) {
                byte_val |= (1 << (7 - bit_idx));
            }
            bit_idx++;
            if (bit_idx == 8) {
                fprintf(out, "%s0x%02X,", (count % 12 == 0) ? "\n    " : " ", byte_val);
                byte_val = 0;
                bit_idx = 0;
                count++;
            }
        }
    }
    if (bit_idx > 0) {
        fprintf(out, "%s0x%02X,", (count % 12 == 0) ? "\n    " : " ", byte_val);
        count++;
    }
    fprintf(out, "\n};\n");
    
    cairo_destroy(g_cr);
    cairo_surface_destroy(surface);
}

void generate_font(const char* font_path, const char* name, int* sizes, int sizes_count, uint32_t* codepoints, int cp_count) {
    FT_Library ft_library;
    FT_Init_FreeType(&ft_library);
    
    FT_Face ft_face;
    if (FT_New_Face(ft_library, font_path, 0, &ft_face)) {
        fprintf(stderr, "Failed to load font %s\n", font_path);
        return;
    }
    
    cairo_font_face_t *cairo_face = cairo_ft_font_face_create_for_ft_face(ft_face, 0);
    
    // Dummy surface for context
    cairo_surface_t *surface = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, 10, 10);
    cairo_t *cr = cairo_create(surface);

    cairo_font_options_t *font_opts = cairo_font_options_create();
    cairo_font_options_set_antialias(font_opts, CAIRO_ANTIALIAS_NONE);
    cairo_font_options_set_hint_style(font_opts, CAIRO_HINT_STYLE_FULL);
    cairo_font_options_set_hint_metrics(font_opts, CAIRO_HINT_METRICS_ON);

    qsort(codepoints, cp_count, sizeof(uint32_t), compare_codepoints);
    
    for (int s = 0; s < sizes_count; s++) {
        int size = sizes[s];
        
        // Get font metrics
        cairo_set_font_face(cr, cairo_face);
        cairo_set_font_size(cr, size);
        cairo_font_extents_t font_extents;
        cairo_font_extents(cr, &font_extents);
        
        fprintf(out, "// Font: %s %d\n", name, size);
        
        // Generate glyphs
        for (int i = 0; i < cp_count; i++) {
            render_glyph(cr, cairo_face, size, codepoints[i], name, font_opts);
        }
        
        // Generate map function
        fprintf(out, "const glyphs_%s_%d = [_]Glyph{\n", name, size);
        
        for (int i = 0; i < cp_count; i++) {
            uint32_t cp = codepoints[i];
            
            // Re-calculate dimensions for the struct
            cairo_text_extents_t extents;
            char utf8[5];
            if (cp < 0x80) { utf8[0] = (char)cp; utf8[1] = 0; }
            else if (cp < 0x800) { utf8[0] = 0xC0 | (cp >> 6); utf8[1] = 0x80 | (cp & 0x3F); utf8[2] = 0; }
            else { utf8[0] = 0xE0 | (cp >> 12); utf8[1] = 0x80 | ((cp >> 6) & 0x3F); utf8[2] = 0x80 | (cp & 0x3F); utf8[3] = 0; }
            
            cairo_text_extents(cr, utf8, &extents);
            int width = (int)ceil(extents.width) + 2;
            int height = (int)ceil(extents.height) + 2;
            if (width <= 2) width = (int)extents.x_advance;
            if (height <= 2) height = (int)size;
            
            fprintf(out, "    .{ .codepoint = %u, .width = %d, .height = %d, .advance_x = %d, .bearing_x = %d, .bearing_y = %d, .data = &glyph_%s_%d_%u },\n",
                cp, width, height, (int)extents.x_advance, (int)(extents.x_bearing - 1), (int)(extents.y_bearing - 1), name, size, cp);
        }
        
        fprintf(out, "};\n");
        fprintf(out, "pub const %s_%d: Font = .{ .height = %d, .ascent = %d, .descent = %d, .glyphs = &glyphs_%s_%d };\n\n",
            name, size, (int)font_extents.height, (int)font_extents.ascent, (int)font_extents.descent, name, size);
    }
    
    cairo_destroy(cr);
    cairo_font_options_destroy(font_opts);
    cairo_surface_destroy(surface);
    cairo_font_face_destroy(cairo_face);
    FT_Done_Face(ft_face);
    FT_Done_FreeType(ft_library);
}

// NOTE: glyph bitmaps and metrics depend on the installed cairo/FreeType
// versions, and the layout constants in src/display_config.zig are tuned to the
// checked-in output. Regenerating with a different toolchain will shift glyph
// metrics and require re-tuning that layout — diff the result before committing.
int main() {
    out = fopen("src/font_data.zig", "w");
    if (!out) return 1;
    
    write_header();
    
    // Ubuntu Regular
    int ubuntu_sizes[] = {14, 20, 24, 26, 34};
    uint32_t ascii[95];
    for(int i=0; i<95; i++) ascii[i] = 32 + i;
    
    // Add degree symbol (0xB0)
    uint32_t ubuntu_cps[96];
    memcpy(ubuntu_cps, ascii, sizeof(ascii));
    ubuntu_cps[95] = 0xB0; // °
    
    generate_font("lib/fonts/Ubuntu-Regular.ttf", "ubuntu", ubuntu_sizes, 5, ubuntu_cps, 96);
    
    // Material Symbols
    int material_sizes[] = {14, 24, 50};
    uint32_t icons[] = {
        0xe30d, 0xe1ff, 0xe322, 0xf7a4, 0xf168, 0xe80d, 0xe923, 
        0xf090, 0xf09b, 0xe8e8, 0xe2bf, 0xf1ca, 0xe63e, 0xe1da, 0xeb2f
    };
    
    generate_font("lib/fonts/MaterialSymbolsRounded.ttf", "material", material_sizes, 3, icons, 15);
    
    fclose(out);
    return 0;
}
